repos:
  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.1
    hooks:
      - id: build-docs
        args: [ '--cache-dir', 'build/.doctrees', '--html-dir', 'build/html', '--source-dir', 'source' ]
        additional_dependencies:
          - sphinx
          - myst_parser